services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: newsdarpan
      POSTGRES_PASSWORD: newsdarpan_password
      POSTGRES_DB: newsdarpan_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
